<template>
  <div class="preferences-view">
    <SurveyNavigation currentClass="Preferences" :show-regenerate="false" :show-export="false" />

    <section class="preferences-shell">
      <header class="preferences-header">
        <div>
          <h1>Preferences</h1>
          <p>Adjust planning thresholds, naming defaults, and atlas alignment settings.</p>
        </div>
        <div class="preferences-actions">
          <button class="btn btn-secondary" type="button" @click="resetDraft">Reset Form</button>
          <button class="btn btn-outline" type="button" @click="restoreDefaults">Restore Defaults</button>
          <button class="btn btn-primary" type="button" @click="savePreferences">Save Preferences</button>
        </div>
      </header>

      <div class="preferences-grid">
        <section class="card">
          <h2>Galaxy Planner</h2>
          <p class="section-copy">These thresholds drive the runtime warning bands shown during galaxy creation.</p>

          <label class="field">
            <span>Moderate threshold</span>
            <input v-model.number="draft.galaxyPlannerModerateSectorThreshold" type="number" min="1000" step="1000" />
          </label>

          <label class="field">
            <span>Heavy threshold</span>
            <input v-model.number="draft.galaxyPlannerHeavySectorThreshold" type="number" min="1000" step="1000" />
          </label>

          <label class="field">
            <span>Extreme threshold</span>
            <input v-model.number="draft.galaxyPlannerExtremeSectorThreshold" type="number" min="1000" step="1000" />
          </label>
        </section>

        <section class="card">
          <h2>Naming</h2>
          <p class="section-copy">Choose how galaxy and sector names are generated by default.</p>

          <label class="field">
            <span>Galaxy naming mode</span>
            <select v-model="draft.galaxyNameMode">
              <option value="normalized">Normalized</option>
              <option value="mythic">Mythic</option>
              <option value="phonotactic">Phonotactic</option>
            </select>
          </label>

          <label class="field">
            <span>Galaxy mythic theme</span>
            <select v-model="draft.galaxyMythicTheme">
              <option value="all">All</option>
              <option value="greco-roman">Greco-Roman</option>
              <option value="norse">Norse</option>
              <option value="mesopotamian">Mesopotamian</option>
              <option value="egyptian">Egyptian</option>
            </select>
          </label>

          <label class="field">
            <span>Sector naming mode</span>
            <select v-model="draft.sectorNameMode">
              <option value="normalized">Normalized</option>
              <option value="list">Named list</option>
              <option value="phonotactic">Phonotactic</option>
            </select>
          </label>
        </section>

        <section class="card">
          <h2>Text To Speech</h2>
          <p class="section-copy">Control how generated names are spoken in supported browsers.</p>

          <label class="field">
            <span>Actor / voice</span>
            <select v-model="draft.ttsVoiceURI" :disabled="!supportsSpeechSynthesis || !ttsVoiceOptions.length">
              <option value="">Default browser voice</option>
              <option v-for="voice in ttsVoiceOptions" :key="voice.voiceURI" :value="voice.voiceURI">
                {{ voice.label }}
              </option>
            </select>
          </label>

          <label class="field">
            <span>Rate: {{ draft.ttsRate.toFixed(2) }}</span>
            <input v-model.number="draft.ttsRate" type="range" min="0.5" max="1.5" step="0.05" />
          </label>

          <label class="field">
            <span>Pitch: {{ draft.ttsPitch.toFixed(2) }}</span>
            <input v-model.number="draft.ttsPitch" type="range" min="0.5" max="1.5" step="0.05" />
          </label>

          <div class="field-actions">
            <button
              class="btn btn-secondary"
              type="button"
              :disabled="!supportsSpeechSynthesis"
              @click="toggleVoicePreview"
            >
              {{ isTestingVoice ? "Stop Voice Test" : "Test Voice" }}
            </button>
          </div>

          <p class="section-copy section-copy--compact">
            {{
              supportsSpeechSynthesis
                ? ttsVoiceOptions.length
                  ? "These settings apply to name playback in the survey pages."
                  : "Your browser supports speech, but voice choices have not loaded yet."
                : "This browser does not expose speech synthesis, so these settings will have no effect here."
            }}
          </p>
        </section>

        <section class="card">
          <h2>Traveller Atlas</h2>
          <p class="section-copy">
            Manual bias values let you nudge sector and subsector overlays against the hex grid.
          </p>

          <label class="field">
            <span>Grid bias X</span>
            <input v-model.number="draft.atlasGridBiasX" type="number" step="0.1" />
          </label>

          <label class="field">
            <span>Grid bias Y</span>
            <input v-model.number="draft.atlasGridBiasY" type="number" step="0.1" />
          </label>
        </section>
      </div>

      <p v-if="statusMessage" class="status-message">{{ statusMessage }}</p>
    </section>
  </div>
</template>

<script setup>
import { onBeforeUnmount, onMounted, reactive, ref } from "vue";
import SurveyNavigation from "../../components/common/SurveyNavigation.vue";
import { PREFERENCE_DEFAULTS, usePreferencesStore } from "../../stores/preferencesStore.js";

const preferencesStore = usePreferencesStore();
const statusMessage = ref("");
const ttsVoiceOptions = ref([]);
const supportsSpeechSynthesis = typeof window !== "undefined" && "speechSynthesis" in window;
const isTestingVoice = ref(false);

function stopVoicePreview() {
  if (!supportsSpeechSynthesis) {
    return;
  }

  window.speechSynthesis.cancel();
  isTestingVoice.value = false;
}

function readSpeechVoices() {
  if (!supportsSpeechSynthesis) {
    ttsVoiceOptions.value = [];
    return;
  }

  const voices = window.speechSynthesis.getVoices();
  ttsVoiceOptions.value = voices.map((voice) => ({
    voiceURI: voice.voiceURI,
    label: `${voice.name}${voice.lang ? ` (${voice.lang})` : ""}${voice.default ? " • default" : ""}`,
  }));
}

onMounted(() => {
  if (!supportsSpeechSynthesis) {
    return;
  }

  readSpeechVoices();
  window.speechSynthesis.addEventListener("voiceschanged", readSpeechVoices);
});

onBeforeUnmount(() => {
  if (!supportsSpeechSynthesis) {
    return;
  }

  stopVoicePreview();
  window.speechSynthesis.removeEventListener("voiceschanged", readSpeechVoices);
});

function toggleVoicePreview() {
  if (!supportsSpeechSynthesis) {
    statusMessage.value = "Text to speech is not supported in this browser.";
    return;
  }

  if (isTestingVoice.value) {
    stopVoicePreview();
    statusMessage.value = "Stopped voice preview.";
    return;
  }

  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance("Eclipsed Horizons sector name preview.");
  utterance.rate = Math.min(1.5, Math.max(0.5, Number(draft.ttsRate) || PREFERENCE_DEFAULTS.ttsRate));
  utterance.pitch = Math.min(1.5, Math.max(0.5, Number(draft.ttsPitch) || PREFERENCE_DEFAULTS.ttsPitch));

  const selectedVoiceURI = String(draft.ttsVoiceURI || "").trim();
  if (selectedVoiceURI) {
    const selectedVoice = window.speechSynthesis.getVoices().find((voice) => voice.voiceURI === selectedVoiceURI);
    if (selectedVoice) {
      utterance.voice = selectedVoice;
    }
  }

  utterance.onend = () => {
    isTestingVoice.value = false;
  };
  utterance.onerror = () => {
    isTestingVoice.value = false;
    statusMessage.value = "Unable to play voice preview.";
  };

  isTestingVoice.value = true;
  statusMessage.value = "Playing voice preview.";
  window.speechSynthesis.speak(utterance);
}

function createDraft(source) {
  return {
    galaxyPlannerModerateSectorThreshold: Number(source.galaxyPlannerModerateSectorThreshold),
    galaxyPlannerHeavySectorThreshold: Number(source.galaxyPlannerHeavySectorThreshold),
    galaxyPlannerExtremeSectorThreshold: Number(source.galaxyPlannerExtremeSectorThreshold),
    galaxyNameMode: String(source.galaxyNameMode || PREFERENCE_DEFAULTS.galaxyNameMode),
    galaxyMythicTheme: String(source.galaxyMythicTheme || PREFERENCE_DEFAULTS.galaxyMythicTheme),
    sectorNameMode: String(source.sectorNameMode || PREFERENCE_DEFAULTS.sectorNameMode),
    ttsRate: Number(source.ttsRate ?? PREFERENCE_DEFAULTS.ttsRate),
    ttsPitch: Number(source.ttsPitch ?? PREFERENCE_DEFAULTS.ttsPitch),
    ttsVoiceURI: String(source.ttsVoiceURI || PREFERENCE_DEFAULTS.ttsVoiceURI),
    atlasGridBiasX: Number(source.atlasGridBiasX),
    atlasGridBiasY: Number(source.atlasGridBiasY),
  };
}

const draft = reactive(createDraft(preferencesStore.$state));

function applyDraft(source) {
  Object.assign(draft, createDraft(source));
}

function resetDraft() {
  applyDraft(preferencesStore.$state);
  statusMessage.value = "Reverted form changes.";
}

function restoreDefaults() {
  preferencesStore.reset();
  applyDraft(preferencesStore.$state);
  statusMessage.value = "Restored default preferences.";
}

function savePreferences() {
  const moderate = Math.max(
    1000,
    Number(draft.galaxyPlannerModerateSectorThreshold) || PREFERENCE_DEFAULTS.galaxyPlannerModerateSectorThreshold,
  );
  const heavy = Math.max(
    moderate + 1,
    Number(draft.galaxyPlannerHeavySectorThreshold) || PREFERENCE_DEFAULTS.galaxyPlannerHeavySectorThreshold,
  );
  const extreme = Math.max(
    heavy + 1,
    Number(draft.galaxyPlannerExtremeSectorThreshold) || PREFERENCE_DEFAULTS.galaxyPlannerExtremeSectorThreshold,
  );

  preferencesStore.replace({
    ...preferencesStore.$state,
    galaxyPlannerModerateSectorThreshold: moderate,
    galaxyPlannerHeavySectorThreshold: heavy,
    galaxyPlannerExtremeSectorThreshold: extreme,
    galaxyNameMode: draft.galaxyNameMode,
    galaxyMythicTheme: draft.galaxyMythicTheme,
    sectorNameMode: draft.sectorNameMode,
    ttsRate: Math.min(1.5, Math.max(0.5, Number(draft.ttsRate) || PREFERENCE_DEFAULTS.ttsRate)),
    ttsPitch: Math.min(1.5, Math.max(0.5, Number(draft.ttsPitch) || PREFERENCE_DEFAULTS.ttsPitch)),
    ttsVoiceURI: String(draft.ttsVoiceURI || ""),
    atlasGridBiasX: Number(draft.atlasGridBiasX) || 0,
    atlasGridBiasY: Number(draft.atlasGridBiasY) || 0,
  });

  applyDraft(preferencesStore.$state);
  statusMessage.value = "Preferences saved.";
}
</script>

<style scoped>
.preferences-view {
  min-height: calc(100vh - 60px);
  background: linear-gradient(180deg, #08101e 0%, #111a31 100%);
}

.preferences-shell {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.preferences-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 1.5rem;
  margin-bottom: 1.75rem;
}

.preferences-header h1 {
  font-size: 2rem;
  color: #f4f7ff;
  margin-bottom: 0.4rem;
}

.preferences-header p {
  color: #9ca6c6;
  max-width: 55ch;
}

.preferences-actions {
  display: flex;
  gap: 0.75rem;
  flex-wrap: wrap;
}

.preferences-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1rem;
}

.card {
  background: rgba(12, 21, 40, 0.88);
  border: 1px solid rgba(88, 116, 170, 0.45);
  border-radius: 16px;
  padding: 1.25rem;
  box-shadow: 0 14px 30px rgba(0, 0, 0, 0.25);
}

.card h2 {
  color: #8ad7ff;
  font-size: 1.1rem;
  margin-bottom: 0.35rem;
}

.section-copy {
  color: #94a0c2;
  font-size: 0.92rem;
  margin-bottom: 1rem;
}

.section-copy--compact {
  margin-bottom: 0;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 0.45rem;
  margin-bottom: 1rem;
}

.field-actions {
  display: flex;
  justify-content: flex-start;
  margin-bottom: 1rem;
}

.field span {
  color: #dbe6ff;
  font-size: 0.92rem;
}

.field input,
.field select {
  width: 100%;
  border: 1px solid rgba(111, 144, 206, 0.55);
  border-radius: 10px;
  background: rgba(4, 10, 24, 0.9);
  color: #eef4ff;
  padding: 0.72rem 0.8rem;
}

.status-message {
  margin-top: 1.25rem;
  color: #8ad7ff;
}

.btn {
  border: 1px solid transparent;
  border-radius: 999px;
  cursor: pointer;
  font-weight: 600;
  padding: 0.7rem 1rem;
}

.btn-primary {
  background: #2b8cff;
  color: #f7fbff;
}

.btn-secondary {
  background: #243250;
  color: #eef4ff;
}

.btn-outline {
  background: transparent;
  color: #8ad7ff;
  border-color: rgba(138, 215, 255, 0.6);
}

@media (max-width: 800px) {
  .preferences-shell {
    padding: 1.25rem;
  }

  .preferences-header {
    flex-direction: column;
  }
}
</style>
