name: Deploy Wiki to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install -r requirements.txt

      - run: mkdocs build

      - uses: actions/upload-pages-artifact@v2
        with:
          path: "./site"

      - uses: actions/deploy-pages@v1
